### ISSUE TITLE
Deadcode in `jvm-function-invoker`

### ISSUE THREAD

**Issue by edmorley** [heroku/buildpacks-jvm#403]
I happened to notice that `JvmFunctionInvokerBuildpackError::CouldNotWriteLaunchToml` is unused:
https://github.com/heroku/buildpacks-jvm/blob/1fd4e44152950657e65d94bb007c00f4fc6e09e9/buildpacks/jvm-function-invoker/src/error.rs#L20-L21

(There may be others)

This is presumably not being picked up by rustc/clippy since `JvmFunctionInvokerBuildpackError` and much of the rest of the buildpack uses `pub` rather than `pub(crate)`, which means the lints don't call out deadcode (even though the crate is binary-only, and doesn't expose a library).

I would recommend moving to `pub(crate)` to catch these in the future.

cc @Malax

**Comment by Malax** [comment]
Ha, thanks for the report - I'll do a pass over the repo when I have some cycles :)
