### ISSUE TITLE
Investigate moving ECR links in buildpack registry to DockerHub

### ISSUE THREAD

**Issue by Malax** [heroku/buildpacks-jvm#486]
In #485 we migrated to DockerHub. Since the old buildpack registry entries still point to ECR, we cannot decommission the ECR repositories. We should investigate if we are able to move old buildpack releases to DockerHub and change the addresses in the registry.

**Comment by edmorley** [comment]
This was resolved in https://github.com/buildpacks/registry-index/pull/5767.
