### ISSUE TITLE
Use Dependabot to keep Git submodules up to date

### ISSUE THREAD

**Issue by edmorley** [heroku/buildpacks-jvm#601]
It turns out that Dependabot supports updating Git submodules:
https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#package-ecosystem

This could be used to keep these submodules up to date:
https://github.com/heroku/buildpacks-jvm/blob/main/.gitmodules

Currently they are all behind latest, eg:
https://github.com/heroku/buildpacks-jvm/tree/main/buildpacks/sbt -> `sbt-extras @ 32c9686`
vs
https://github.com/dwijnand/sbt-extras/commits/master/

cc @Malax

**Comment by Malax** [comment]
👍🏻
